version: '3.8'

services:
  backend:
    build:
      context: ./server  
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    container_name: mongo_node
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sjce_leave
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
